### ISSUE TITLE
Roadmap - 2022 (规划中)

### ISSUE THREAD

**Issue by WZMIAOMIAO** [WZMIAOMIAO/deep-learning-for-image-processing#425]
图像分类：
- [x] RepVGG
- [x] ConvNeXt
- [x] MobileViT 

目标检测：
- [x] 补上YOLOv4网络讲解
- [x] 补上YOLOv5网络讲解（没有论文）
- [x]  补上YOLOX网络讲解
- [x] 补上Faster RCNN换backbone视频
- [x] FCOS 模型讲解

语义分割：
- [x] DeepLab V3
- [x] LR-ASPP 
- [x] UNet
- [x] U2Net 

实例分割：
- [x] Mask R-CNN 模型讲解
- [x] Mask R-CNN 代码讲解

人体关键点检测：
- [x] HRNet 模型讲解
- [x] HRNet 代码讲解

其他:
- [x] Grad-CAM
- [ ] Mixed precision

**Comment by Mankvis** [comment]
LSTM有计划吗

**Comment by WZMIAOMIAO** [comment]
> LSTM有计划吗

暂时没有

**Comment by Mankvis** [comment]
> > LSTM有计划吗
> 
> 暂时没有

好的，视频中的PPT可以分享吗

**Comment by WZMIAOMIAO** [comment]
> > > LSTM有计划吗
> > 
> > 
> > 暂时没有
> 
> 好的，视频中的PPT可以分享吗

仓库里都有啊，https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/tree/master/course_ppt

**Comment by xdboost** [comment]
GAN有计划吗？

**Comment by WZMIAOMIAO** [comment]
> GAN有计划吗？

今年没有这个打算

**Comment by gewenchao** [comment]
语义分割这块，可以分享一些轻量级的实时语义分割吗，效果和速度兼备，重点还是速度。Deeplab之类的网络太大了，不太中用。

**Comment by WZMIAOMIAO** [comment]
> 语义分割这块，可以分享一些轻量级的实时语义分割吗，效果和速度兼备，重点还是速度。Deeplab之类的网络太大了，不太中用。

之前讲的LR-ASPP可以看下

**Comment by gewenchao** [comment]
> > 语义分割这块，可以分享一些轻量级的实时语义分割吗，效果和速度兼备，重点还是速度。Deeplab之类的网络太大了，不太中用。
> 
> 之前讲的LR-ASPP可以看下

好的，谢谢，期待能讲解更多的实时语义分割

**Comment by happysheep224** [comment]
花分类数据集下载不了了，怎么办呀

**Comment by happysheep224** [comment]
可以多讲讲轻量化的网络吗？另外，up主有关注剪枝吗？

**Comment by WZMIAOMIAO** [comment]
> 花分类数据集下载不了了，怎么办呀

链接: https://pan.baidu.com/s/1LHlCw3b9bExoNOH8wUMN-g  密码: 967m

**Comment by Ctu-SiTuShenPeng** [comment]
大佬，会有ocr板块吗

**Comment by WZMIAOMIAO** [comment]
> 大佬，会有ocr板块吗
暂时不考虑哦，推荐你看下PaddleOCR的仓库，里面文档什么的都很齐全，社区也很活跃。
[https://github.com/PaddlePaddle/PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)

**Comment by shangshanghuiliyi** [comment]
您好，我最近想做一个图像篡改检测的系统（就是检测拼接和copymove那种），请问您觉得哪种模型效果可能比较好或者有较大的优化空间呢，谢谢！

**Comment by WZMIAOMIAO** [comment]
> 您好，我最近想做一个图像篡改检测的系统（就是检测拼接和copymove那种），请问您觉得哪种模型效果可能比较好或者有较大的优化空间呢，谢谢！

抱歉，我对你说的领域不太了解。

**Comment by 1042754389** [comment]
![image](https://user-images.githubusercontent.com/101400433/157861431-8f5bf80a-ea9e-4300-b960-785d7a12b01c.png)
您好 请问这个界面的文件怎么下载呀（谢谢~）

**Comment by WZMIAOMIAO** [comment]
> ![image](https://user-images.githubusercontent.com/101400433/157861431-8f5bf80a-ea9e-4300-b960-785d7a12b01c.png) 您好 请问这个界面的文件怎么下载呀（谢谢~）

看下这个视频：https://www.bilibili.com/video/BV1NZ4y1G7QG

**Comment by 1042754389** [comment]
啊啊啊啊真的太感谢您了！！！（up主太善良了太善良了 爱死你了）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月11日(星期五) 晚上7:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] Roadmap - 2022 (规划中) (Issue #425)





  
 您好 请问这个界面的文件怎么下载呀（谢谢~）
  
看下这个视频：https://www.bilibili.com/video/BV1NZ4y1G7QG
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PotentialX** [comment]
图像增强和tensorboard有计划么？

**Comment by WZMIAOMIAO** [comment]
> 图像增强和tensorboard有计划么？

图像增强就那么几种感觉没什么好讲的，暂不考虑。
tensorboard之前讲过了: https://www.bilibili.com/video/BV1Qf4y1C7kz

**Comment by PotentialX** [comment]
那常用的 loss funcion 有没有考虑做一个合集？

**Comment by WZMIAOMIAO** [comment]
> 那常用的 loss funcion 有没有考虑做一个合集？

没有

**Comment by QQR1** [comment]
up导，可不可出一期部署的教程，libtorch，tensorRT, openvino之类的

**Comment by WZMIAOMIAO** [comment]
> up导，可不可出一期部署的教程，libtorch，tensorRT, openvino之类的

后期会考虑

**Comment by shangshanghuiliyi** [comment]
你好，我搭建了你给的ssd模型，用了我自己的数据集然后出现了

 area = (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0])
IndexError: too many indices for tensor of dimension 1
请问是怎么回事呢

**Comment by shangshanghuiliyi** [comment]
有时候box的size会是0，是不是因为这个原因

**Comment by shangshanghuiliyi** [comment]
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.，还一块报了这个错

**Comment by WZMIAOMIAO** [comment]
> 你好，我搭建了你给的ssd模型，用了我自己的数据集然后出现了
> 
> area = (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0]) IndexError: too many indices for tensor of dimension 1 请问是怎么回事呢

 和规划无关的问题请不要在此提问了。其他问题，请单独开个issue。

**Comment by jafer11** [comment]
实例分割SOLOv1和SOLOv2有计划吗？

**Comment by XavierYorke** [comment]
up主，请问3D语义分割和3D目标检测有计划吗

**Comment by wahihihi** [comment]
请教一下up主，您公司在生产环境的部署策略是什么样？
我是做自动驾驶的，想请教一下您是否了解图像分类，目标识别，应用到移动端相关生产环境部署策略？
谢谢

**Comment by WZMIAOMIAO** [comment]
> 请教一下up主，您公司在生产环境的部署策略是什么样？ 我是做自动驾驶的，想请教一下您是否了解图像分类，目标识别，应用到移动端相关生产环境部署策略？ 谢谢

移动端部署这块我不太清楚，根据我有限的了解，如果移动端有NVIDIA GPU设备可以考虑转成tensorrt格式部署，如果只有intel的CPU设备可以考虑转成openvino格式部署。

**Comment by Pengchuang** [comment]
请问，基于deeplabV3+网络的输出结果再进行目标检测任务的这种方式，可行吗？如果可行的话，有什么参考例程吗？谢谢

**Comment by jump666666** [comment]
File "G:\anaconda3.5\envs\my0515\lib\argparse.py", line 338, in _format_usage
    assert ' '.join(pos_parts) == pos_usage
AssertionError
请问在用pytorch做VIT花分类的代码 报这个错是什么意思呢

**Comment by tqinger** [comment]
请问那个模型部署部分我看您在之前的视频基础上有更新，如果没空出视频，能不能出一个readme呀

**Comment by 1429483125** [comment]
霹导，有考虑讲MLPs吗？

**Comment by davidpengiupui** [comment]
大佬有考虑讲VideoPose3D吗？

**Comment by zxw223311** [comment]
预测脚本中，这种类型的报错因为什么呀？
RuntimeError: Error(s) in loading state_dict for FasterRCNN:
	Missing key(s) in state_dict: "backbone.body.conv1.weight", "backbone.body.bn1.weight", "backbone.body.bn1.bias", "backbone.body.bn1.running_mean", "backbone.body.bn1.running_var", "backbone.body.layer1.0.conv1.weight", "backbone.body.layer1.0.bn1.weight", "backbone.body.layer1.0.bn1.bias", "backbone.body.layer1.0.bn1.running_mean", "backbone.body.layer1.0.bn1.running_var", "backbone.body.layer1.0.conv2.weight", "backbone.body.layer1.0.bn2.weight", "backbone.body.layer1.0.bn2.bias", "backbone.body.layer1.0.bn2.running_mean", "backbone.body.layer1.0.bn2.running_var", "backbone.body.layer1.0.conv3.weight", "backbone.body.layer1.0.bn3.weight", "backbone.body.layer1.0.bn3.bias", "backbone.body.layer1.0.bn3.running_mean", "backbone.body.layer1.0.bn3.running_var", "backbone.body.layer1.0.downsample.0.weight", "backbone.body.layer1.0.downsample.1.weight", "backbone.body.layer1.0.downsample.1.bias", "backbone.body.layer1.0.downsample.1.running_mean", "backbone.body.layer1.0.downsample.1.running_var", "backbone.body.layer1.1.conv1.weight", "backbone.body.layer1.1.bn1.weight", "backbone.body.layer1.1.bn1.bias", "backbone.body.layer1.1.bn1.running_mean", "backbone.body.layer1.1.bn1.running_var", "backbone.body.layer1.1.conv2.weight", "backbone.body.layer1.1.bn2.weight", "backbone.body.layer1.1.bn2.bias", "backbone.body.layer1.1.bn2.running_mean", "backbone.body.layer1.1.bn2.running_var", "backbone.body.layer1.1.conv3.weight", "backbone.body.layer1.1.bn3.weight", "backbone.body.layer1.1.bn3.bias", "backbone.body.layer1.1.bn3.running_mean", "backbone.body.layer1.1.bn3.running_var", "backbone.body.layer1.2.conv1.weight", "backbone.body.layer1.2.bn1.weight", "backbone.body.layer1.2.bn1.bias", "backbone.body.layer1.2.bn1.running_mean", "backbone.body.layer1.2.bn1.running_var", "backbone.body.layer1.2.conv2.weight", "backbone.body.layer1.2.bn2.weight", "backbone.body.layer1.2.bn2.bias", "backbone.body.layer1.2.bn2.running_mean", "backbone.body.layer1.2.bn2.running_var", "backbone.body.layer1.2.conv3.weight", "backbone.body.layer1.2.bn3.weight", "backbone.body.layer1.2.bn3.bias", "backbone.body.layer1.2.bn3.running_mean", "backbone.body.layer1.2.bn3.running_var", "backbone.body.layer2.0.conv1.weight", "backbone.body.layer2.0.bn1.weight", "backbone.body.layer2.0.bn1.bias", "backbone.body.layer2.0.bn1.running_mean", "backbone.body.layer2.0.bn1.running_var", "backbone.body.layer2.0.conv2.weight", "backbone.body.layer2.0.bn2.weight", "backbone.body.layer2.0.bn2.bias", "backbone.body.layer2.0.bn2.running_mean", "backbone.body.layer2.0.bn2.running_var", "backbone.body.layer2.0.conv3.weight", "backbone.body.layer2.0.bn3.weight", "backbone.body.layer2.0.bn3.bias", "backbone.body.layer2.0.bn3.running_mean", "backbone.body.layer2.0.bn3.running_var", "backbone.body.layer2.0.downsample.0.weight", "backbone.body.layer2.0.downsample.1.weight", "backbone.body.layer2.0.downsample.1.bias", "backbone.body.layer2.0.downsample.1.running_mean", "backbone.body.layer2.0.downsample.1.running_var", "backbone.body.layer2.1.conv1.weight", "backbone.body.layer2.1.bn1.weight", "backbone.body.layer2.1.bn1.bias", "backbone.body.layer2.1.bn1.running_mean", "backbone.body.layer2.1.bn1.running_var", "backbone.body.layer2.1.conv2.weight", "backbone.body.layer2.1.bn2.weight", "backbone.body.layer2.1.bn2.bias", "backbone.body.layer2.1.bn2.running_mean", "backbone.body.layer2.1.bn2.running_var", "backbone.body.layer2.1.conv3.weight", "backbone.body.layer2.1.bn3.weight", "backbone.body.layer2.1.bn3.bias", "backbone.body.layer2.1.bn3.running_mean", "backbone.body.layer2.1.bn3.running_var", "backbone.body.layer2.2.conv1.weight", "backbone.body.layer2.2.bn1.weight", "backbone.body.layer2.2.bn1.bias", "backbone.body.layer2.2.bn1.running_mean", "backbone.body.layer2.2.bn1.running_var", "backbone.body.layer2.2.conv2.weight", "backbone.body.layer2.2.bn2.weight", "backbone.body.layer2.2.bn2.bias", "backbone.body.layer2.2.bn2.running_mean", "backbone.body.layer2.2.bn2.running_var", "backbone.body.layer2.2.conv3.weight", "backbone.body.layer2.2.bn3.weight", "backbone.body.layer2.2.bn3.bias", "backbone.body.layer2.2.bn3.running_mean", "backbone.body.layer2.2.bn3.running_var", "backbone.body.layer2.3.conv1.weight", "backbone.body.layer2.3.bn1.weight", "backbone.body.layer2.3.bn1.bias", "backbone.body.layer2.3.bn1.running_mean", "backbone.body.layer2.3.bn1.running_var", "backbone.body.layer2.3.conv2.weight", "backbone.body.layer2.3.bn2.weight", "backbone.body.layer2.3.bn2.bias", "backbone.body.layer2.3.bn2.running_mean", "backbone.body.layer2.3.bn2.running_var", "backbone.body.layer2.3.conv3.weight", "backbone.body.layer2.3.bn3.weight", "backbone.body.layer2.3.bn3.bias", "backbone.body.layer2.3.bn3.running_mean", "backbone.body.layer2.3.bn3.running_var", "backbone.body.layer3.0.conv1.weight", "backbone.body.layer3.0.bn1.weight", "backbone.body.layer3.0.bn1.bias", "backbone.body.layer3.0.bn1.running_mean", "backbone.body.layer3.0.bn1.running_var", "backbone.body.layer3.0.conv2.weight", "backbone.body.layer3.0.bn2.weight", "backbone.body.layer3.0.bn2.bias", "backbone.body.layer3.0.bn2.running_mean", "backbone.body.layer3.0.bn2.running_var", "backbone.body.layer3.0.conv3.weight", "backbone.body.layer3.0.bn3.weight", "backbone.body.layer3.0.bn3.bias", "backbone.body.layer3.0.bn3.running_mean", "backbone.body.layer3.0.bn3.running_var", "backbone.body.layer3.0.downsample.0.weight", "backbone.body.layer3.0.downsample.1.weight", "backbone.body.layer3.0.downsample.1.bias", "backbone.body.layer3.0.downsample.1.running_mean", "backbone.body.layer3.0.downsample.1.running_var", "backbone.body.layer3.1.conv1.weight", "backbone.body.layer3.1.bn1.weight", "backbone.body.layer3.1.bn1.bias", "backbone.body.layer3.1.bn1.running_mean", "backbone.body.layer3.1.bn1.running_var", "backbone.body.layer3.1.conv2.weight", "backbone.body.layer3.1.bn2.weight", "backbone.body.layer3.1.bn2.bias", "backbone.body.layer3.1.bn2.running_mean", "backbone.body.layer3.1.bn2.running_var", "backbone.body.layer3.1.conv3.weight", "backbone.body.layer3.1.bn3.weight", "backbone.body.layer3.1.bn3.bias", "backbone.body.layer3.1.bn3.running_mean", "backbone.body.layer3.1.bn3.running_var", "backbone.body.layer3.2.conv1.weight", "backbone.body.layer3.2.bn1.weight", "backbone.body.layer3.2.bn1.bias", "backbone.body.layer3.2.bn1.running_mean", "backbone.body.layer3.2.bn1.running_var", "backbone.body.layer3.2.conv2.weight", "backbone.body.layer3.2.bn2.weight", "backbone.body.layer3.2.bn2.bias", "backbone.body.layer3.2.bn2.running_mean", "backbone.body.layer3.2.bn2.running_var", "backbone.body.layer3.2.conv3.weight", "backbone.body.layer3.2.bn3.weight", "backbone.body.layer3.2.bn3.bias", "backbone.body.layer3.2.bn3.running_mean", "backbone.body.layer3.2.bn3.running_var", "backbone.body.layer3.3.conv1.weight", "backbone.body.layer3.3.bn1.weight", "backbone.body.layer3.3.bn1.bias", "backbone.body.layer3.3.bn1.running_mean", "backbone.body.layer3.3.bn1.running_var", "backbone.body.layer3.3.conv2.weight", "backbone.body.layer3.3.bn2.weight", "backbone.body.layer3.3.bn2.bias", "backbone.body.layer3.3.bn2.running_mean", "backbone.body.layer3.3.bn2.running_var", "backbone.body.layer3.3.conv3.weight", "backbone.body.layer3.3.bn3.weight", "backbone.body.layer3.3.bn3.bias", "backbone.body.layer3.3.bn3.running_mean", "backbone.body.layer3.3.bn3.running_var", "backbone.body.layer3.4.conv1.weight", "backbone.body.layer3.4.bn1.weight", "backbone.body.layer3.4.bn1.bias", "backbone.body.layer3.4.bn1.running_mean", "backbone.body.layer3.4.bn1.running_var", "backbone.body.layer3.4.conv2.weight", "backbone.body.layer3.4.bn2.weight", "backbone.body.layer3.4.bn2.bias", "backbone.body.layer3.4.bn2.running_mean", "backbone.body.layer3.4.bn2.running_var", "backbone.body.layer3.4.conv3.weight", "backbone.body.layer3.4.bn3.weight", "backbone.body.layer3.4.bn3.bias", "backbone.body.layer3.4.bn3.running_mean", "backbone.body.layer3.4.bn3.running_var", "backbone.body.layer3.5.conv1.weight", "backbone.body.layer3.5.bn1.weight", "backbone.body.layer3.5.bn1.bias", "backbone.body.layer3.5.bn1.running_mean", "backbone.body.layer3.5.bn1.running_var", "backbone.body.layer3.5.conv2.weight", "backbone.body.layer3.5.bn2.weight", "backbone.body.layer3.5.bn2.bias", "backbone.body.layer3.5.bn2.running_mean", "backbone.body.layer3.5.bn2.running_var", "backbone.body.layer3.5.conv3.weight", "backbone.body.layer3.5.bn3.weight", "backbone.body.layer3.5.bn3.bias", "backbone.body.layer3.5.bn3.running_mean", "backbone.body.layer3.5.bn3.running_var", "backbone.body.layer4.0.conv1.weight", "backbone.body.layer4.0.bn1.weight", "backbone.body.layer4.0.bn1.bias", "backbone.body.layer4.0.bn1.running_mean", "backbone.body.layer4.0.bn1.running_var", "backbone.body.layer4.0.conv2.weight", "backbone.body.layer4.0.bn2.weight", "backbone.body.layer4.0.bn2.bias", "backbone.body.layer4.0.bn2.running_mean", "backbone.body.layer4.0.bn2.running_var", "backbone.body.layer4.0.conv3.weight", "backbone.body.layer4.0.bn3.weight", "backbone.body.layer4.0.bn3.bias", "backbone.body.layer4.0.bn3.running_mean", "backbone.body.layer4.0.bn3.running_var", "backbone.body.layer4.0.downsample.0.weight", "backbone.body.layer4.0.downsample.1.weight", "backbone.body.layer4.0.downsample.1.bias", "backbone.body.layer4.0.downsample.1.running_mean", "backbone.body.layer4.0.downsample.1.running_var", "backbone.body.layer4.1.conv1.weight", "backbone.body.layer4.1.bn1.weight", "backbone.body.layer4.1.bn1.bias", "backbone.body.layer4.1.bn1.running_mean", "backbone.body.layer4.1.bn1.running_var", "backbone.body.layer4.1.conv2.weight", "backbone.body.layer4.1.bn2.weight", "backbone.body.layer4.1.bn2.bias", "backbone.body.layer4.1.bn2.running_mean", "backbone.body.layer4.1.bn2.running_var", "backbone.body.layer4.1.conv3.weight", "backbone.body.layer4.1.bn3.weight", "backbone.body.layer4.1.bn3.bias", "backbone.body.layer4.1.bn3.running_mean", "backbone.body.layer4.1.bn3.running_var", "backbone.body.layer4.2.conv1.weight", "backbone.body.layer4.2.bn1.weight", "backbone.body.layer4.2.bn1.bias", "backbone.body.layer4.2.bn1.running_mean", "backbone.body.layer4.2.bn1.running_var", "backbone.body.layer4.2.conv2.weight", "backbone.body.layer4.2.bn2.weight", "backbone.body.layer4.2.bn2.bias", "backbone.body.layer4.2.bn2.running_mean", "backbone.body.layer4.2.bn2.running_var", "backbone.body.layer4.2.conv3.weight", "backbone.body.layer4.2.bn3.weight", "backbone.body.layer4.2.bn3.bias", "backbone.body.layer4.2.bn3.running_mean", "backbone.body.layer4.2.bn3.running_var", "backbone.fpn.inner_blocks.0.weight", "backbone.fpn.inner_blocks.0.bias", "backbone.fpn.inner_blocks.1.weight", "backbone.fpn.inner_blocks.1.bias", "backbone.fpn.inner_blocks.2.weight", "backbone.fpn.inner_blocks.2.bias", "backbone.fpn.inner_blocks.3.weight", "backbone.fpn.inner_blocks.3.bias", "backbone.fpn.layer_blocks.0.weight", "backbone.fpn.layer_blocks.0.bias", "backbone.fpn.layer_blocks.1.weight", "backbone.fpn.layer_blocks.1.bias", "backbone.fpn.layer_blocks.2.weight", "backbone.fpn.layer_blocks.2.bias", "backbone.fpn.layer_blocks.3.weight", "backbone.fpn.layer_blocks.3.bias".

**Comment by B1INGO** [comment]
十分感谢！

**Comment by lamsongianm** [comment]
請問model.py 只包含MobileViT block? 還是有包含了 MV2?

**Comment by WZMIAOMIAO** [comment]
> 請問model.py 只包含MobileViT block? 還是有包含了 MV2?

都有，详情看这个视频：https://www.bilibili.com/video/BV1ae411L7Ki

**Comment by zxw223311** [comment]
> 請問model.py 只包含MobileViT block? 還是有包含了 MV2?
都有，问题已解决

**Comment by DMUgjj** [comment]
能出一期详解transformer吗？ up主

**Comment by QQR1** [comment]
导师，有打算出MLOps的内容吗，培养一下我们的工程能力

**Comment by UestcJay** [comment]
导师，有计划进军3D 检测吗？ 我觉得可以出一个系列
